/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SubscriptionRequiredImport } from './routes/subscription-required'
import { Route as OrganizationFormImport } from './routes/organizationForm'
import { Route as AboutImport } from './routes/about'
import { Route as LayoutImport } from './routes/_layout'
import { Route as AuthImport } from './routes/_auth'
import { Route as AuthIndexImport } from './routes/_auth/index'
import { Route as ContractsIdImport } from './routes/contracts.$id'
import { Route as LayoutReportsImport } from './routes/_layout.reports'
import { Route as LayoutRentsImport } from './routes/_layout.rents'
import { Route as LayoutOrganizationImport } from './routes/_layout.organization'
import { Route as LayoutDashboardImport } from './routes/_layout.dashboard'
import { Route as LayoutClientsImport } from './routes/_layout.clients'
import { Route as LayoutAccountSettingsImport } from './routes/_layout.account-settings'
import { Route as AuthVerifyEmailImport } from './routes/_auth/verify-email'
import { Route as AuthSignupImport } from './routes/_auth/signup'
import { Route as AuthResetPasswordImport } from './routes/_auth/reset-password'
import { Route as AuthLoginImport } from './routes/_auth/login'
import { Route as LayoutCustomerDetailsIdImport } from './routes/_layout.customerDetails.$id'
import { Route as LayoutCarDetailsIdImport } from './routes/_layout.carDetails.$id'
import { Route as LayoutAdminDashboardImport } from './routes/_layout.admin.dashboard'

// Create/Update Routes

const SubscriptionRequiredRoute = SubscriptionRequiredImport.update({
  id: '/subscription-required',
  path: '/subscription-required',
  getParentRoute: () => rootRoute,
} as any)

const OrganizationFormRoute = OrganizationFormImport.update({
  id: '/organizationForm',
  path: '/organizationForm',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)

const ContractsIdRoute = ContractsIdImport.update({
  id: '/contracts/$id',
  path: '/contracts/$id',
  getParentRoute: () => rootRoute,
} as any)

const LayoutReportsRoute = LayoutReportsImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutRentsRoute = LayoutRentsImport.update({
  id: '/rents',
  path: '/rents',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutOrganizationRoute = LayoutOrganizationImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutDashboardRoute = LayoutDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutClientsRoute = LayoutClientsImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAccountSettingsRoute = LayoutAccountSettingsImport.update({
  id: '/account-settings',
  path: '/account-settings',
  getParentRoute: () => LayoutRoute,
} as any)

const AuthVerifyEmailRoute = AuthVerifyEmailImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)

const AuthSignupRoute = AuthSignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)

const AuthResetPasswordRoute = AuthResetPasswordImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)

const LayoutCustomerDetailsIdRoute = LayoutCustomerDetailsIdImport.update({
  id: '/customerDetails/$id',
  path: '/customerDetails/$id',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutCarDetailsIdRoute = LayoutCarDetailsIdImport.update({
  id: '/carDetails/$id',
  path: '/carDetails/$id',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAdminDashboardRoute = LayoutAdminDashboardImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/organizationForm': {
      id: '/organizationForm'
      path: '/organizationForm'
      fullPath: '/organizationForm'
      preLoaderRoute: typeof OrganizationFormImport
      parentRoute: typeof rootRoute
    }
    '/subscription-required': {
      id: '/subscription-required'
      path: '/subscription-required'
      fullPath: '/subscription-required'
      preLoaderRoute: typeof SubscriptionRequiredImport
      parentRoute: typeof rootRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof AuthImport
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordImport
      parentRoute: typeof AuthImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupImport
      parentRoute: typeof AuthImport
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailImport
      parentRoute: typeof AuthImport
    }
    '/_layout/account-settings': {
      id: '/_layout/account-settings'
      path: '/account-settings'
      fullPath: '/account-settings'
      preLoaderRoute: typeof LayoutAccountSettingsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/clients': {
      id: '/_layout/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof LayoutClientsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/organization': {
      id: '/_layout/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof LayoutOrganizationImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/rents': {
      id: '/_layout/rents'
      path: '/rents'
      fullPath: '/rents'
      preLoaderRoute: typeof LayoutRentsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/reports': {
      id: '/_layout/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof LayoutReportsImport
      parentRoute: typeof LayoutImport
    }
    '/contracts/$id': {
      id: '/contracts/$id'
      path: '/contracts/$id'
      fullPath: '/contracts/$id'
      preLoaderRoute: typeof ContractsIdImport
      parentRoute: typeof rootRoute
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof AuthImport
    }
    '/_layout/admin/dashboard': {
      id: '/_layout/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof LayoutAdminDashboardImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/carDetails/$id': {
      id: '/_layout/carDetails/$id'
      path: '/carDetails/$id'
      fullPath: '/carDetails/$id'
      preLoaderRoute: typeof LayoutCarDetailsIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/customerDetails/$id': {
      id: '/_layout/customerDetails/$id'
      path: '/customerDetails/$id'
      fullPath: '/customerDetails/$id'
      preLoaderRoute: typeof LayoutCustomerDetailsIdImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface LayoutRouteChildren {
  LayoutAccountSettingsRoute: typeof LayoutAccountSettingsRoute
  LayoutClientsRoute: typeof LayoutClientsRoute
  LayoutDashboardRoute: typeof LayoutDashboardRoute
  LayoutOrganizationRoute: typeof LayoutOrganizationRoute
  LayoutRentsRoute: typeof LayoutRentsRoute
  LayoutReportsRoute: typeof LayoutReportsRoute
  LayoutAdminDashboardRoute: typeof LayoutAdminDashboardRoute
  LayoutCarDetailsIdRoute: typeof LayoutCarDetailsIdRoute
  LayoutCustomerDetailsIdRoute: typeof LayoutCustomerDetailsIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAccountSettingsRoute: LayoutAccountSettingsRoute,
  LayoutClientsRoute: LayoutClientsRoute,
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutOrganizationRoute: LayoutOrganizationRoute,
  LayoutRentsRoute: LayoutRentsRoute,
  LayoutReportsRoute: LayoutReportsRoute,
  LayoutAdminDashboardRoute: LayoutAdminDashboardRoute,
  LayoutCarDetailsIdRoute: LayoutCarDetailsIdRoute,
  LayoutCustomerDetailsIdRoute: LayoutCustomerDetailsIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteWithChildren
  '/about': typeof AboutRoute
  '/organizationForm': typeof OrganizationFormRoute
  '/subscription-required': typeof SubscriptionRequiredRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/account-settings': typeof LayoutAccountSettingsRoute
  '/clients': typeof LayoutClientsRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/organization': typeof LayoutOrganizationRoute
  '/rents': typeof LayoutRentsRoute
  '/reports': typeof LayoutReportsRoute
  '/contracts/$id': typeof ContractsIdRoute
  '/': typeof AuthIndexRoute
  '/admin/dashboard': typeof LayoutAdminDashboardRoute
  '/carDetails/$id': typeof LayoutCarDetailsIdRoute
  '/customerDetails/$id': typeof LayoutCustomerDetailsIdRoute
}

export interface FileRoutesByTo {
  '': typeof LayoutRouteWithChildren
  '/about': typeof AboutRoute
  '/organizationForm': typeof OrganizationFormRoute
  '/subscription-required': typeof SubscriptionRequiredRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/account-settings': typeof LayoutAccountSettingsRoute
  '/clients': typeof LayoutClientsRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/organization': typeof LayoutOrganizationRoute
  '/rents': typeof LayoutRentsRoute
  '/reports': typeof LayoutReportsRoute
  '/contracts/$id': typeof ContractsIdRoute
  '/': typeof AuthIndexRoute
  '/admin/dashboard': typeof LayoutAdminDashboardRoute
  '/carDetails/$id': typeof LayoutCarDetailsIdRoute
  '/customerDetails/$id': typeof LayoutCustomerDetailsIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_layout': typeof LayoutRouteWithChildren
  '/about': typeof AboutRoute
  '/organizationForm': typeof OrganizationFormRoute
  '/subscription-required': typeof SubscriptionRequiredRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/_layout/account-settings': typeof LayoutAccountSettingsRoute
  '/_layout/clients': typeof LayoutClientsRoute
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/_layout/organization': typeof LayoutOrganizationRoute
  '/_layout/rents': typeof LayoutRentsRoute
  '/_layout/reports': typeof LayoutReportsRoute
  '/contracts/$id': typeof ContractsIdRoute
  '/_auth/': typeof AuthIndexRoute
  '/_layout/admin/dashboard': typeof LayoutAdminDashboardRoute
  '/_layout/carDetails/$id': typeof LayoutCarDetailsIdRoute
  '/_layout/customerDetails/$id': typeof LayoutCustomerDetailsIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/about'
    | '/organizationForm'
    | '/subscription-required'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/account-settings'
    | '/clients'
    | '/dashboard'
    | '/organization'
    | '/rents'
    | '/reports'
    | '/contracts/$id'
    | '/'
    | '/admin/dashboard'
    | '/carDetails/$id'
    | '/customerDetails/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/about'
    | '/organizationForm'
    | '/subscription-required'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/account-settings'
    | '/clients'
    | '/dashboard'
    | '/organization'
    | '/rents'
    | '/reports'
    | '/contracts/$id'
    | '/'
    | '/admin/dashboard'
    | '/carDetails/$id'
    | '/customerDetails/$id'
  id:
    | '__root__'
    | '/_auth'
    | '/_layout'
    | '/about'
    | '/organizationForm'
    | '/subscription-required'
    | '/_auth/login'
    | '/_auth/reset-password'
    | '/_auth/signup'
    | '/_auth/verify-email'
    | '/_layout/account-settings'
    | '/_layout/clients'
    | '/_layout/dashboard'
    | '/_layout/organization'
    | '/_layout/rents'
    | '/_layout/reports'
    | '/contracts/$id'
    | '/_auth/'
    | '/_layout/admin/dashboard'
    | '/_layout/carDetails/$id'
    | '/_layout/customerDetails/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LayoutRoute: typeof LayoutRouteWithChildren
  AboutRoute: typeof AboutRoute
  OrganizationFormRoute: typeof OrganizationFormRoute
  SubscriptionRequiredRoute: typeof SubscriptionRequiredRoute
  ContractsIdRoute: typeof ContractsIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LayoutRoute: LayoutRouteWithChildren,
  AboutRoute: AboutRoute,
  OrganizationFormRoute: OrganizationFormRoute,
  SubscriptionRequiredRoute: SubscriptionRequiredRoute,
  ContractsIdRoute: ContractsIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/_layout",
        "/about",
        "/organizationForm",
        "/subscription-required",
        "/contracts/$id"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/login",
        "/_auth/reset-password",
        "/_auth/signup",
        "/_auth/verify-email",
        "/_auth/"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/account-settings",
        "/_layout/clients",
        "/_layout/dashboard",
        "/_layout/organization",
        "/_layout/rents",
        "/_layout/reports",
        "/_layout/admin/dashboard",
        "/_layout/carDetails/$id",
        "/_layout/customerDetails/$id"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/organizationForm": {
      "filePath": "organizationForm.tsx"
    },
    "/subscription-required": {
      "filePath": "subscription-required.tsx"
    },
    "/_auth/login": {
      "filePath": "_auth/login.tsx",
      "parent": "/_auth"
    },
    "/_auth/reset-password": {
      "filePath": "_auth/reset-password.tsx",
      "parent": "/_auth"
    },
    "/_auth/signup": {
      "filePath": "_auth/signup.tsx",
      "parent": "/_auth"
    },
    "/_auth/verify-email": {
      "filePath": "_auth/verify-email.tsx",
      "parent": "/_auth"
    },
    "/_layout/account-settings": {
      "filePath": "_layout.account-settings.tsx",
      "parent": "/_layout"
    },
    "/_layout/clients": {
      "filePath": "_layout.clients.tsx",
      "parent": "/_layout"
    },
    "/_layout/dashboard": {
      "filePath": "_layout.dashboard.tsx",
      "parent": "/_layout"
    },
    "/_layout/organization": {
      "filePath": "_layout.organization.tsx",
      "parent": "/_layout"
    },
    "/_layout/rents": {
      "filePath": "_layout.rents.tsx",
      "parent": "/_layout"
    },
    "/_layout/reports": {
      "filePath": "_layout.reports.tsx",
      "parent": "/_layout"
    },
    "/contracts/$id": {
      "filePath": "contracts.$id.tsx"
    },
    "/_auth/": {
      "filePath": "_auth/index.tsx",
      "parent": "/_auth"
    },
    "/_layout/admin/dashboard": {
      "filePath": "_layout.admin.dashboard.tsx",
      "parent": "/_layout"
    },
    "/_layout/carDetails/$id": {
      "filePath": "_layout.carDetails.$id.tsx",
      "parent": "/_layout"
    },
    "/_layout/customerDetails/$id": {
      "filePath": "_layout.customerDetails.$id.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
