/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as OrganizationImport } from './routes/organization'
import { Route as LoginImport } from './routes/login'
import { Route as AboutImport } from './routes/about'
import { Route as LayoutImport } from './routes/_layout'
import { Route as AuthImport } from './routes/_auth'
import { Route as AuthIndexImport } from './routes/_auth/index'
import { Route as LayoutRentsImport } from './routes/_layout.rents'
import { Route as LayoutDashboardImport } from './routes/_layout.dashboard'
import { Route as LayoutCarDetailsIdImport } from './routes/_layout.carDetails.$id'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const OrganizationRoute = OrganizationImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)

const LayoutRentsRoute = LayoutRentsImport.update({
  id: '/rents',
  path: '/rents',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutDashboardRoute = LayoutDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutCarDetailsIdRoute = LayoutCarDetailsIdImport.update({
  id: '/carDetails/$id',
  path: '/carDetails/$id',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/organization': {
      id: '/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof OrganizationImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/rents': {
      id: '/_layout/rents'
      path: '/rents'
      fullPath: '/rents'
      preLoaderRoute: typeof LayoutRentsImport
      parentRoute: typeof LayoutImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof AuthImport
    }
    '/_layout/carDetails/$id': {
      id: '/_layout/carDetails/$id'
      path: '/carDetails/$id'
      fullPath: '/carDetails/$id'
      preLoaderRoute: typeof LayoutCarDetailsIdImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface LayoutRouteChildren {
  LayoutDashboardRoute: typeof LayoutDashboardRoute
  LayoutRentsRoute: typeof LayoutRentsRoute
  LayoutCarDetailsIdRoute: typeof LayoutCarDetailsIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutRentsRoute: LayoutRentsRoute,
  LayoutCarDetailsIdRoute: LayoutCarDetailsIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/organization': typeof OrganizationRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/rents': typeof LayoutRentsRoute
  '/': typeof AuthIndexRoute
  '/carDetails/$id': typeof LayoutCarDetailsIdRoute
}

export interface FileRoutesByTo {
  '': typeof LayoutRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/organization': typeof OrganizationRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/rents': typeof LayoutRentsRoute
  '/': typeof AuthIndexRoute
  '/carDetails/$id': typeof LayoutCarDetailsIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_layout': typeof LayoutRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/organization': typeof OrganizationRoute
  '/signup': typeof SignupRoute
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/_layout/rents': typeof LayoutRentsRoute
  '/_auth/': typeof AuthIndexRoute
  '/_layout/carDetails/$id': typeof LayoutCarDetailsIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/about'
    | '/login'
    | '/organization'
    | '/signup'
    | '/dashboard'
    | '/rents'
    | '/'
    | '/carDetails/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/about'
    | '/login'
    | '/organization'
    | '/signup'
    | '/dashboard'
    | '/rents'
    | '/'
    | '/carDetails/$id'
  id:
    | '__root__'
    | '/_auth'
    | '/_layout'
    | '/about'
    | '/login'
    | '/organization'
    | '/signup'
    | '/_layout/dashboard'
    | '/_layout/rents'
    | '/_auth/'
    | '/_layout/carDetails/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LayoutRoute: typeof LayoutRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  OrganizationRoute: typeof OrganizationRoute
  SignupRoute: typeof SignupRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LayoutRoute: LayoutRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  OrganizationRoute: OrganizationRoute,
  SignupRoute: SignupRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/_layout",
        "/about",
        "/login",
        "/organization",
        "/signup"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/dashboard",
        "/_layout/rents",
        "/_layout/carDetails/$id"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/organization": {
      "filePath": "organization.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/_layout/dashboard": {
      "filePath": "_layout.dashboard.tsx",
      "parent": "/_layout"
    },
    "/_layout/rents": {
      "filePath": "_layout.rents.tsx",
      "parent": "/_layout"
    },
    "/_auth/": {
      "filePath": "_auth/index.tsx",
      "parent": "/_auth"
    },
    "/_layout/carDetails/$id": {
      "filePath": "_layout.carDetails.$id.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
